# Umbra OS — lightdm greeter (only seen if autologin is off or after logout).
[greeter]
theme-name = Yaru-purple-dark
icon-theme-name = Papirus-Dark
cursor-theme-name = Bibata-Modern-Ice
background = /usr/share/backgrounds/umbra/wallpaper.png
font-name = Inter 11
xft-antialias = true
xft-hintstyle = slight
indicator-spacing = 8
position = 50%,center 58%,center
clock-format = %H:%M  ·  %a %b %d
show-clock = true
panel-position = top
